CREATE TABLESPACE CUSTOMER_DATA DATAFILE SIZE 100M AUTOEXTEND ON MAXSIZE 40G;
CREATE TABLESPACE CUSTOMER_INDX DATAFILE SIZE 100M AUTOEXTEND ON MAXSIZE 40G;

---User Created CUSTOMER------

CREATE USER CUSTOMER
  IDENTIFIED BY sybT#lt001
  DEFAULT TABLESPACE CUSTOMER_DATA
  TEMPORARY TABLESPACE TEMP;
--------Granted Privileges -------
grant EXECUTE_CATALOG_ROLE to CUSTOMER;
grant SELECT_CATALOG_ROLE  to CUSTOMER;
grant 
CREATE ANY PROCEDURE
,CREATE ANY SYNONYM
,CREATE ANY TRIGGER
,CREATE SEQUENCE
,CREATE SESSION
,CREATE SYNONYM
,CREATE TABLE
,CREATE VIEW
, GRANT ANY OBJECT PRIVILEGE to CUSTOMER;
--Check privileges -----

select * from dba_sys_privs where grantee='CUSTOMER';

--Create user Loyalty_user-------
CREATE USER LOYALTY_USER
  IDENTIFIED BY sybT#lt01
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;
  
CREATE ROLE LOYALTY_USER_ROLE;

grant create session to LOYALTY_USER;

---User namespace file 

ALTER USER "CUSTOMER"
DEFAULT TABLESPACE "CUSTOMER_DATA"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

ALTER USER "CUSTOMER" QUOTA UNLIMITED ON CUSTOMER_INDX;
ALTER USER "CUSTOMER" QUOTA UNLIMITED ON CUSTOMER_DATA;

ALTER USER "LOYALTY_USER" identified by sybT#lt01
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;


